In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
pd.read_csv('Customer.csv')

    Age  Gender Education   Review Purchased
0    30  Female    School  Average        No
1    68  Female        UG     Poor        No
2    70  Female        PG     Good        No
3    72  Female        PG     Good        No
4    16  Female        UG  Average        No
5    31  Female    School  Average       Yes
6    18    Male    School     Good        No
7    60  Female    School     Poor       Yes
8    65  Female        UG  Average        No
9    74    Male        UG     Good       Yes
10   98  Female        UG     Good       Yes
11   74    Male        UG     Good       Yes
12   51    Male    School     Poor        No
13   57  Female    School  Average        No
14   15    Male        PG     Poor       Yes
15   75    Male        UG     Poor        No
16   59    Male        UG     Poor       Yes
17   22  Female        UG     Poor       Yes
18   19    Male    School     Good        No
19   97    Male        PG     Poor       Yes
20   57  Female    School  Average       Yes
21   32    Male        PG  Average        No
22   18  Female        PG     Poor       Yes
23   96  Female    School     Good        No
24   16  Female        PG  Average       Yes
25   57  Female    School     Good        No
26   53  Female        PG     Poor        No
27   69  Female        PG     Poor        No
28   48    Male    School     Poor        No
29   83  Female        UG  Average       Yes
30   73    Male        UG  Average        No
31   22  Female    School     Poor       Yes
32   92    Male        UG  Average       Yes
33   89  Female        PG     Good       Yes
34   86    Male    School  Average        No
35   74    Male    School     Poor       Yes
36   34  Female        UG     Good       Yes
37   94    Male        PG  Average       Yes
38   45  Female    School     Good        No
39   76    Male        PG     Poor        No
40   39    Male    School     Good        No
41   23    Male        PG     Good       Yes
42   30  Female        PG     Good       Yes
43   27    Male        PG     Poor        No
44   77  Female        UG  Average        No
45   61    Male        PG     Poor       Yes
46   64  Female        PG     Poor        No
47   38  Female        PG     Good       Yes
48   39  Female        UG     Good       Yes
49   25  Female        UG     Good        No

In [3]:
df=pd.read_csv('Customer.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        50 non-null     int64
 1   Gender     50 non-null     object
 2   Education  50 non-null     object
 3   Review     50 non-null     object
 4   Purchased  50 non-null     object
dtypes: int64(1), object(4)
memory usage: 2.1+ KB

In [6]:
df1=df.iloc[:,2:4]
df1.head()

  Education   Review
0    School  Average
1        UG     Poor
2        PG     Good
3        PG     Good
4        UG  Average

In [9]:
df1['Review'].value_counts()

Review
Poor       18
Good       18
Average    14
Name: count, dtype: int64

In [10]:
df1['Education'].value_counts()

Education
PG        18
School    16
UG        16
Name: count, dtype: int64

In [15]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[['School','UG','PG'],['Poor','Average','Good']])

df1_oe= oe.fit_transform(df1)
df1_oe

array([[0., 1.],
       [1., 0.],
       [2., 2.],
       [2., 2.],
       [1., 1.],
       [0., 1.],
       [0., 2.],
       [0., 0.],
       [1., 1.],
       [1., 2.],
       [1., 2.],
       [1., 2.],
       [0., 0.],
       [0., 1.],
       [2., 0.],
       [1., 0.],
       [1., 0.],
       [1., 0.],
       [0., 2.],
       [2., 0.],
       [0., 1.],
       [2., 1.],
       [2., 0.],
       [0., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [2., 0.],
       [0., 0.],
       [1., 1.],
       [1., 1.],
       [0., 0.],
       [1., 1.],
       [2., 2.],
       [0., 1.],
       [0., 0.],
       [1., 2.],
       [2., 1.],
       [0., 2.],
       [2., 0.],
       [0., 2.],
       [2., 2.],
       [2., 2.],
       [2., 0.],
       [1., 1.],
       [2., 0.],
       [2., 0.],
       [2., 2.],
       [1., 2.],
       [1., 2.]])

In [21]:
import numpy as np
type(df1_oe)
np.ndarray
df1=pd.DataFrame(df1_oe,columns=['Education','Review'])
df1.head()

   Education  Review
0        0.0     1.0
1        1.0     0.0
2        2.0     2.0
3        2.0     2.0
4        1.0     1.0

In [25]:
df.update(df1)
#  now we update our ordinal categori variable to number format using update method 
# but it you see 'review' & Education coloumn it shown f;oat values 
df.head()

   Age  Gender Education Review Purchased
0   30  Female       0.0    1.0        No
1   68  Female       1.0    0.0        No
2   70  Female       2.0    2.0        No
3   72  Female       2.0    2.0        No
4   16  Female       1.0    1.0        No

In [26]:
df['Review']=df["Review"].astype(int)
df['Education']=df["Education"].astype(int)

In [27]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        50 non-null     int64
 1   Gender     50 non-null     object
 2   Education  50 non-null     int32
 3   Review     50 non-null     int32
 4   Purchased  50 non-null     object
dtypes: int32(2), int64(1), object(2)
memory usage: 1.7+ KB

In [31]:
#lable encoder 
df2=df[['Gender','Purchased']]
df2.head()

   Gender Purchased
0  Female        No
1  Female        No
2  Female        No
3  Female        No
4  Female        No

In [33]:
from sklearn.preprocessing import LabelEncoder
le=LabelEncoder()

df2["Gender_encoder"]=le.fit_transform(df2["Gender"])
df2["Purchased_encoder"]=le.fit_transform(df2["Purchased"])

C:\Users\Kiran Maske\AppData\Local\Temp\ipykernel_16560\981659049.py:4: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Gender_encoder"]=le.fit_transform(df2["Gender"])
C:\Users\Kiran Maske\AppData\Local\Temp\ipykernel_16560\981659049.py:5: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  df2["Purchased_encoder"]=le.fit_transform(df2["Purchased"])

In [34]:
df2.head()

   Gender Purchased  Gender_encoder  Purchased_encoder
0  Female        No               0                  0
1  Female        No               0                  0
2  Female        No               0                  0
3  Female        No               0                  0
4  Female        No               0                  0

In [36]:
df[['Gender','Purchased']]=df2[['Gender_encoder','Purchased_encoder']].copy()
df.head()

   Age  Gender  Education  Review  Purchased
0   30       0          0       1          0
1   68       0          1       0          0
2   70       0          2       2          0
3   72       0          2       2          0
4   16       0          1       1          0

In [37]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 50 entries, 0 to 49
Data columns (total 5 columns):
 #   Column     Non-Null Count  Dtype
---  ------     --------------  -----
 0   Age        50 non-null     int64
 1   Gender     50 non-null     int32
 2   Education  50 non-null     int32
 3   Review     50 non-null     int32
 4   Purchased  50 non-null     int32
dtypes: int32(4), int64(1)
memory usage: 1.3 KB

In [39]:
df.to_csv('customer_encoder.csv')  # dowload file 
import os  #see location 
os.getcwd()

'D:\\machine'