In [2]:
import pandas as pd

In [6]:
l1=['a','b','c']
df=pd.DataFrame(l1)
df

   0
0  a
1  b
2  c

In [5]:
#from list of list creat Dataframe 
l1=[[1,2,3],[4,5,6]]
df=pd.DataFrame(l1)
df

   0  1  2
0  1  2  3
1  4  5  6

In [7]:
#from dictionary creat data fraame 
d1={'ID':[11,12,13,14],'SN':[1,2,3,4]}
df=pd.DataFrame(d1)
df

   ID  SN
0  11   1
1  12   2
2  13   3
3  14   4