In [1]:
import numpy as np
import pandas as pd
import seaborn as sns 
import matplotlib.pyplot as plt

In [2]:
pd.read_csv('Result_Student.csv')

,Student ID,Class,Study hrs,Social Media usage hrs,Percentage,Grade,Gender
0,1001,10,2,3,50,Avg,Female
1,1002,10,6,2,80,Vgood,Male
2,1003,10,3,2,60,Good,Female
3,1004,11,0,1,45,Fail,Male
4,1005,12,5,2,75,Good,Female

In [3]:
df=pd.read_csv('Result_Student.csv')

In [4]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Student ID              5 non-null      int64
 1   Class                   5 non-null      int64
 2   Study hrs               5 non-null      int64
 3   Social Media usage hrs  5 non-null      int64
 4   Percentage              5 non-null      int64
 5   Grade                   5 non-null      object
 6   Gender                  5 non-null      object
dtypes: int64(5), object(2)
memory usage: 408.0+ bytes

In [27]:
df1=df.iloc[:,5:6]
df1.head()

   Grade
0    Avg
1  Vgood
2   Good
3   Fail
4   Good

In [28]:
df1['Grade'].value_counts()

Grade
Good     2
Avg      1
Vgood    1
Fail     1
Name: count, dtype: int64

In [46]:
df1['Gender'].value_counts()

KeyError: 'Gender'

In [29]:
from sklearn.preprocessing import OrdinalEncoder
oe=OrdinalEncoder(categories=[['Avg','Vgood','Good','Fail']])

df1_oe= oe.fit_transform(df1)
df1_oe

array([[0.],
       [1.],
       [2.],
       [3.],
       [2.]])

In [42]:
import numpy as np
type(df1_oe)
np.ndarray
df1=pd.DataFrame(df1_oe,columns=['Grade'])
df1.head()

   Grade
0    0.0
1    1.0
2    2.0
3    3.0
4    2.0

In [43]:
df.update(df1)
df.head()

,Student ID,Class,Study hrs,Social Media usage hrs,Percentage,Grade,Gender
0,1001,10,2,3,50,0.0,0.0
1,1002,10,6,2,80,1.0,1.0
2,1003,10,3,2,60,2.0,0.0
3,1004,11,0,1,45,3.0,1.0
4,1005,12,5,2,75,2.0,0.0

In [44]:
df['Grade']=df["Grade"].astype(int)

In [47]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Student ID              5 non-null      int64
 1   Class                   5 non-null      int64
 2   Study hrs               5 non-null      int64
 3   Social Media usage hrs  5 non-null      int64
 4   Percentage              5 non-null      int64
 5   Grade                   5 non-null      int32
 6   Gender                  5 non-null      object
dtypes: int32(1), int64(5), object(1)
memory usage: 388.0+ bytes

In [48]:
#lable encoder 
df2=df[['Grade','Gender']]
df2.head()

   Grade Gender
0      0    0.0
1      1    1.0
2      2    0.0
3      3    1.0
4      2    0.0

In [49]:
df.update(df2)

In [50]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 5 entries, 0 to 4
Data columns (total 7 columns):
 #   Column                  Non-Null Count  Dtype
---  ------                  --------------  -----
 0   Student ID              5 non-null      int64
 1   Class                   5 non-null      int64
 2   Study hrs               5 non-null      int64
 3   Social Media usage hrs  5 non-null      int64
 4   Percentage              5 non-null      int64
 5   Grade                   5 non-null      int32
 6   Gender                  5 non-null      object
dtypes: int32(1), int64(5), object(1)
memory usage: 388.0+ bytes

In [ ]:
df.to_csv('_encoder.csv')  # dowload file 
import os  #see location 
os.getcwd()